
name: urticaria
channels:
   - conda-forge
dependencies:
  - jupyter
  - nbformat
  - nbconvert
  - pytest
  - pytesseract
  - pdfminer.six
  - pdf2image
  - pandas
  - PIL
  - numpy
  - python-dotenv
  - multiprocessing